/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPlayersIndexRouteImport } from './routes/_app/players/index'
import { Route as AppGamesIndexRouteImport } from './routes/_app/games/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppPlayersPlayerIndexRouteImport } from './routes/_app/players/$player/index'
import { Route as AppGamesGameIndexRouteImport } from './routes/_app/games/$game/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPlayersIndexRoute = AppPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPlayersPlayerIndexRoute = AppPlayersPlayerIndexRouteImport.update({
  id: '/players/$player/',
  path: '/players/$player/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppGamesGameIndexRoute = AppGamesGameIndexRouteImport.update({
  id: '/games/$game/',
  path: '/games/$game/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/games/': typeof AppGamesIndexRoute
  '/players/': typeof AppPlayersIndexRoute
  '/games/$game/': typeof AppGamesGameIndexRoute
  '/players/$player/': typeof AppPlayersPlayerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/games': typeof AppGamesIndexRoute
  '/players': typeof AppPlayersIndexRoute
  '/games/$game': typeof AppGamesGameIndexRoute
  '/players/$player': typeof AppPlayersPlayerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/games/': typeof AppGamesIndexRoute
  '/_app/players/': typeof AppPlayersIndexRoute
  '/_app/games/$game/': typeof AppGamesGameIndexRoute
  '/_app/players/$player/': typeof AppPlayersPlayerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/games/'
    | '/players/'
    | '/games/$game/'
    | '/players/$player/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/games'
    | '/players'
    | '/games/$game'
    | '/players/$player'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/dashboard/'
    | '/_app/games/'
    | '/_app/players/'
    | '/_app/games/$game/'
    | '/_app/players/$player/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/players/': {
      id: '/_app/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AppPlayersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/players/$player/': {
      id: '/_app/players/$player/'
      path: '/players/$player'
      fullPath: '/players/$player/'
      preLoaderRoute: typeof AppPlayersPlayerIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/games/$game/': {
      id: '/_app/games/$game/'
      path: '/games/$game'
      fullPath: '/games/$game/'
      preLoaderRoute: typeof AppGamesGameIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
  AppPlayersIndexRoute: typeof AppPlayersIndexRoute
  AppGamesGameIndexRoute: typeof AppGamesGameIndexRoute
  AppPlayersPlayerIndexRoute: typeof AppPlayersPlayerIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
  AppPlayersIndexRoute: AppPlayersIndexRoute,
  AppGamesGameIndexRoute: AppGamesGameIndexRoute,
  AppPlayersPlayerIndexRoute: AppPlayersPlayerIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
